apiVersion: v1
kind: ConfigMap
metadata:
  name: brows3r-config
  namespace: brows3r
data:
  DATABASE_URL: "postgres://brows3r:password@postgres:5432/brows3r"
  S3_REGION: "us-east-1"
  # Override these in production
  # S3_URL: "https://s3.amazonaws.com"
  # S3_BUCKET: "your-bucket-name"
