apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brows3r
  namespace: brows3r
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - brows3r.example.com
    secretName: brows3r-tls
  rules:
  - host: brows3r.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: brows3r
            port:
              number: 80
