apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: brows3r

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: brows3r
  app.kubernetes.io/version: "0.1.0"
