apiVersion: v1
kind: Service
metadata:
  name: brows3r-metrics
  namespace: brows3r
  labels:
    app: brows3r
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: metrics
  selector:
    app: brows3r
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: brows3r
  namespace: brows3r
  labels:
    app: brows3r
spec:
  selector:
    matchLabels:
      app: brows3r
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
